app1/app/urls.py
from django.contrib import admin
from django.urls import path, include
from app import settings
from main import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('users.urls', namespace='user'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app1/main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile_list/', views.profile_list, name="profile_list"),
    path('places/', views.places, name='places')
]

app1/users/urls.py
from django.urls import path
from app import settings
from users import views
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('edit_profile/', views.UserEditView.as_view(), name='edit_profile'),
    path('list/', views.list_images, name='list_images'),
    path('list_achivements/', views.list_images_achivements, name='list_achive'),
    path('list_equipments/', views.equipments, name='list_equipments'),
    path("post/<int:pk>", views.PostDeatailView.as_view(), name='post_deatail'),
    #path("profile/<int:pk>", views.other_profile, name="other_profile")
]

app1/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <title> ЛовиЛодку </title>
    <head>
        {% block css %} {% endblock  %}
        <link rel="stylesheet" href="{% static "deps\css\home.css" %}">
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <div class="rectangle_menu">
            <a class="logo_menu" href="{% url "main:index" %}">ЛОВИЛОДКУ</a>
            <div class="menu text">
                <a href="{% url "main:profile_list" %}"><div class="menu_galery">ПОЛЬЗОВАТЕЛИ</div></a>
                <a href="{% url "main:places" %}"><div class="menu_location">МЕСТА РЫБАЛКИ</div></a>
                <a href="{% url "user:list_equipments" %}"><div class="menu_thing">СНАРЯЖЕНИЕ</div>
                {% if not user.is_authenticated %}
                    <a class="button_login" href="{% url "user:login" %}"> <button class="text">Войти</button></a>
                    <a class="button_registration text" href="{% url "user:registration" %}"> <button class="text"> Регистрация </button></a>
                    {% else %}
                    <a class="button_profile" href="{% url "user:profile" %}"> <button class="text">Профиль </button></a>
                    <a class="button_logout" href="{% url "user:logout" %}"> <button class="text"> Выйти </button></a>
                {% endif %}
            </div>
        </div>
        {% block content %} {% endblock  %}
    </body>
</html>

app1/templates/post.html
{% extends "base.html" %}
{% load static %}

{% block css %}

{% endblock  %}

{% block content %}
    <img src="{{upload_images.image.url}}">
{% endblock %}