app1/app/urls.py
from django.contrib import admin
from django.urls import path, include
from app import settings
from main import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('users.urls', namespace='user'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app1/users/urls.py
from django.urls import path
from app import settings
from users import views
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('edit_profile/', views.UserEditView.as_view(), name='edit_profile'),
    path('list/', views.list_images, name='list_images'),
    path('list_achivements/', views.list_images_achivements, name='list_achive'),
    path('list_equipments/', views.equipments, name='list_equipments'),
    path("post/<int:pk>", views.PostDeatailView.as_view(), name='post_deatail'),
    #path("profile/<int:pk>", views.other_profile, name="other_profile")
]

app1/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')
    phone_number = models.CharField(max_length=10, blank=True, null=True)
    about = models.CharField(max_length= 300, blank=True, null=True)
    first_name = models.CharField(max_length=100, blank=True, null=True)
    cat = models.ForeignKey('Upload_images', on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

class Upload_images(models.Model):
    user_id = models.CharField(max_length=20, null=True, blank=True)
    image = models.ImageField(upload_to="images")
    category = models.CharField(max_length=256, null=True, blank=True)
    likes = models.ManyToManyField(User, related_name='image_posts')

app1/users/forms.py
from pyexpat.errors import messages
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.urls import reverse_lazy
from users.models import Upload_images, User


    
class UserLoginForm(AuthenticationForm):
    username = forms.CharField()                              
    password = forms.CharField()
    class Meta():
        model = User
        fields = ['username', 'password']

class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            #"first_name",
            #"last_name",
            "username",
            "email",
            "password1",
            "password2",
        )
    
    #first_name = forms.CharField()
    #last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class UploadForm(forms.ModelForm):
    class Meta:
        model = Upload_images
        fields={'image'}
        
class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "about",)
            #"email",)

    image = forms.ImageField(required=False)
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    username = forms.CharField()
    about = forms.CharField(required=False)
    
    #email = forms.CharField()

class EditProfileForm(forms.ModelForm):
    image = forms.ImageField(required=False)
    email = forms.EmailField(max_length=100, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    username = forms.CharField(max_length=40, widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name=forms.CharField(max_length=40, widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    last_name=forms.CharField(max_length=40, widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    about = forms.CharField(max_length=300, widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    class Meta:
        model=User
        fields=("email", "username", "first_name", "last_name", "about", "image")

app1/users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy

from django.core.paginator import Paginator
from users.forms import ProfileForm, UploadForm, UserLoginForm, UserRegistrationForm, EditProfileForm
from users.models import Upload_images, User

class UserEditView(generic.UpdateView):
    form_class = EditProfileForm
    template_name = r'users\edit_profile.html'
    success_url = reverse_lazy('users:profile')
    def get_object(self):
        return self.request.user

class PostDeatailView(generic.DeleteView):
    model = Upload_images
    template_name = "post.html"

#def other_profile(request, pk):
    #if request.user.is_authenticated:
    #    profile = User.objects.get(pk=pk)
    #    return render(request, "users/profile.html", {"profile": profile})
    #else:
    #    return redirect("index")


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)

            session_key = request.session.session_key

            if user:
                auth.login(request, user)
                messages.success(request, f"{username}, Вы вошли в аккаунт")

                

                redirect_page = request.POST.get('next', None)
                if redirect_page and redirect_page != reverse('user:logout'):
                    return HttpResponseRedirect(request.POST.get('next'))
                    
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()

    return render(request, 'users/login.html')


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()

            session_key = request.session.session_key

            user = form.instance
            auth.login(request, user)

            
            messages.success(request, f"{user.username}, Вы успешно зарегистрированы и вошли в аккаунт")
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()
    return render(request, 'users/registration.html')

@login_required
def profile(request):
    #if request.user.is_authenticated:
        #profile = User.objects.get(id=pk)
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Профайл успешно обновлен")
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)
    users_uploads = Upload_images.objects.filter(user_id=request.user.id)
    count_default = Upload_images.objects.filter(user_id=request.user.id, category="defoult").count()
    count_achive = Upload_images.objects.filter(user_id=request.user.id, category="achivements").count()
    all_count = count_default + count_achive
    context = {
        'form': form,
        'users_uploads': users_uploads,
        'count': all_count,
        #"profile": profile
    }
    return render(request, 'users/profile.html', context)

def list_images(request):
    if request.method == "POST":
        Upload_images.objects.create(user_id=request.user.id,
                                     image=request.FILES.get('image'),
                                     category="defoult")
        #form = UploadForm(request.POST, request.FILES)
        #if form.is_valid():
            #form.save()
   # else:
        #context = {'form': UploadForm(request.POST, request.FILES)}
        #return render(request, 'users/list.html', context)
    users_uploads = Upload_images.objects.filter(user_id=request.user.id)
    context = {'form': UploadForm(), 'users_uploads': users_uploads}
    return render(request, 'users/list.html', context)

def list_images_achivements(request):
    if request.method == "POST":
        Upload_images.objects.create(
            user_id=request.user.id,
            image=request.FILES.get('image'),
            category='achivements')
    users_uploads = Upload_images.objects.filter(user_id=request.user.id)
    context = {'form': UploadForm(), 'users_uploads': users_uploads }
    return render(request, 'users/list_achive.html', context)
    
def equipments(request):
    if request.method == "POST":
        Upload_images.objects.create(
            user_id=request.user.id,
            image=request.FILES.get('image'),
            category='equipments')
    users_uploads = Upload_images.objects.filter(user_id=request.user.id)
    context = {'form': UploadForm(), 'users_uploads': users_uploads }
    return render(request, 'users/equipments.html', context)

@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, Вы вышли из аккаунта")
    auth.logout(request)
    return redirect(reverse('main:index'))

app1/users/templates/users/edit_profile.html
{% extends "base.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static "deps\css\edit.css" %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
{% endblock  %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <section class="edit-container">
            
        <div class="edit-block">
            <div>
                <h3>Имя</h3>
                <input type="text" class="input name" name="first_name" placeholder="Имя" value="{{form.first_name.value|default_if_none:''}}">
            </div>
            <div>
                <h3>Фамилия</h3>
                <input type="text" class="input family-name" name="last_name" placeholder="Фамилия" value="{{form.last_name.value|default_if_none:''}}">
            </div>
            <div>
                <h3>О себе</h3>
                <input maxlength="62" minlength="10" type="text" class="input about" name="about" placeholder="О себе" value="{{form.about.value|default_if_none:''}}">
            </div>
        </div>
        <div class="edit-block">
            <div>
                <h3>Никнейм</h3>
                <input type="text" class="input nickname" name="username" placeholder="Никнейм" value="{{form.username.value}}">
            </div>
            <div>
                <h3>Почта</h3>
                <input type="text" class="input email" name="email" placeholder="Почта" value="{{form.email.value}}">
                
            </div>
        </div>
        <div class="edit-block">
            <h3>Фото</h3>
            {% if user.image %}
                <div class="photo"><img src="{{user.image.url}}" id="avatar"></div>
            {% else %}
                <img src="{% static "deps/image/defoult_profile.jpg" %}"
                        alt="Аватар пользователя" class="img-fluid rounded-circle" id="avatar">
            {% endif %}
            <form method="post" enctype="multipart/form-data">
                <label class="input-file">
                       <input type="file" id="id_image" name='image' accept="image/*">    
                       <span>Выберите файл</span>
                 </label>
            </form>
            {% if form.image.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{form.image.errors}}</div>
            {% endif %}
            <button type="submit" class="save">Сохранить</button>
        </div>
    </section>
    <!--<input type="text" class="edit_username" name="username" placeholder="Ник" value="{{form.username.value}}" required>
    {{form.email}}
    <input type="text" name="about" placeholder="Расскажите о себе" value="{{form.about.value}}" required>
    <input type="file" id="id_image"
    name='image'
    accept="image/*">
    {% if form.image.errors %}
    <div class="alert alert-danger alert-dismissible fade show">{{form.image.errors}}</div>
    {% endif %}
    <button type="submit" class="submit_editor text">Подтвердить изменение профиля</button>
</form>-->
{% endblock  %}

app1/users/templates/users/equipments.html
{% extends "base.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static "deps/css/list.css" %}">

{%endblock%}

{% block content %}
<div class="achv-container">
    <h3>Снаряжение</h3>
    <div class="form_for_upload_images">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.image}}
            <input type="submit" value="Submit">
        </form>
    </div>
    {% for image in users_uploads %}
        {% if image.category == "equipments" %}
            <img src="{{image.image.url}}" id="upload_images">
        {% endif %}
    {% endfor %}
</div>
{% endblock%}

app1/users/templates/users/list.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static "deps/css/list.css" %}">
{% endblock  %}

{% block content %}
<div class="achv-container">
    <h3>Публикация</h3>
<div class="form_for_upload_images">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.image}}
        <input type="submit" value="Submit">
    </form>
</div>
{% for image in users_uploads %}
        <img src="{{image.image.url}}" id="upload_images">
{% endfor %}
</div>
{% endblock content %}

app1/users/templates/users/list_achive.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static "deps/css/list.css" %}">
{% endblock  %}

{% block content %}
<div class="achv-container">
    <h3>Достижения</h3>
    <div class="form_for_upload_images">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.image}}
            <input type="submit" value="Submit">
        </form>
    </div>
    {% for image in users_uploads %}
        {% if image.category == "achivements" %}
            <img src="{{image.image.url}}" id="upload_images">
        {% endif %}
    {% endfor %}
</div>
{% endblock content %}

app1/users/templates/users/login.html
{% extends "base.html" %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps\css\login.css" %}">
{% endblock  %}

{% block content %}
<form  action="{% url "user:login" %}" method="post">
    <div class="register_menu">
        {% csrf_token %}
        {% if request.GET.next %}
            <input type="hidden" name="next" value={{request.GET.next}}>
        {% endif %}
        <div class="register_menu_enter">
            <a class="a_enter" href="">Войти</a>
        </div>
        <div class="register_menu_register">
            <a class="a_register"
            href="{% url "user:registration" %}">Регистрация</a>
        </div>
        
        <input type="text" class="email"
        value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
        name="username" id="id_username"
        placeholder="Ник">

        <input type="password" class="password" name="password" id="id_password" placeholder="Пароль">
        
            <button type="submit" class="enter button_login_reg">Войти</button>
    </div>
</form>
{% endblock  %}

app1/users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static "deps/css/profile.css" %}">
{% endblock  %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="text profile">
            <div class="profile_photo">
                {% if user.image %}
                    <img src="{{ user.image.url }}"
                        alt="Аватар пользователя" class="img-fluid rounded-circle" id="profile_in_photo">
                {% else %}
                    <img src="{% static "deps/image/defoult_profile.jpg" %}"
                        alt="Аватар пользователя" class="img-fluid rounded-circle" id="profile_in_photo">
                {% endif %}
            </div>
            <div class="profile_information">
                <p class="profile_name" type="text", name="first_name" required>{{form.first_name.value|default_if_none:' '}} {{form.last_name.value|default_if_none:' '}}</p>
                <p class="profile_username" type="text" id="id_username" name="username"required> {{form.username.value}} </p>
                <div class="profile_description text">
                    <p>{{form.about.value|default_if_none:' '}}</p>
                </div>
                {% if count > 3 %}
                    <img src="{% static "deps/image/noob.png" %}" alt="звание" class="rank_user">
                {% endif %}
            </div>
            <div>
                <a href="{% url "users:edit_profile" %}"><img src="{% static "deps/image/editor.png" %}" class="button_edit"></a>
            </div>
        </div>
    <a href="{% url "user:list_achive" %}">
        <div class="text achievements">
            <div class="achievements_header">
                <p>достижения</p>
            </div>
            <div class="achievements_medal">
                <img src="{% static "deps/image/medal.png" %}">
                
                <img src="{% static "deps/image/medal_blue_star.png" %}">
                <img src="{% static "deps/image/medal_gold_star.png" %}">
                <img src="{% static "deps/image/medal_fish.png" %}">
            </div>
        </div>
    </a>
<a href="{% url "user:list_equipments" %}">
    <div class="rectangle_equpment">
        <div class="pictures_recomendtion">
        <div class="tent_pofile">
            <img src="{% static "deps/image/tent.png" %}" id="tent_profile">
        </div>
        <div class="fishing_rod_pofile">
            <img src="{% static "deps/image/fishing_rod.png" %}" id="rod_profile">
        </div>
        <div class="boat_pofile">
            <img src="{% static "deps/image/boat.png" %}" id="boat_profile">
        </div>
        <div class="car_pofile">
            <img src="{% static "deps/image/car.png" %}" id="car_profile">
        </div>
    </div>
        <div class="text_equpment text">
            снаряжение
        </div>
    </div>
</a>
</form>
<a href="{% url "user:list_images" %}" class="button_uploads"><button class="text">Создать/Отредактировать</button></a>
<div class="upload_images">
    {% for image in users_uploads %}
        <a href="{% url "user:post_deatail" image.pk %}"><img src="{{image.image.url}}" id="upload_images"></a>
    {% endfor %}
</div>
{% endblock  %}

app1/users/templates/users/registration.html
{% extends "base.html" %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps\css\register.css" %}">
{% endblock  %}

{% block content %}
<form action="{% url "user:registration" %}" method="post">
    <div class="register_menu">
        {% csrf_token %}
        <div class="register_menu_enter">
            <a class="a_enter" href="{% url "user:login" %}">Войти</a>
        </div>
        <div class="register_menu_register">
            <a class="a_register" href="">Регистрация</a>
        </div>
        
        <input type="username" class="name" id="id_username"
        value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
        name="username" placeholder="Ник">
        {% if form.username.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
        {% endif %}
        <input type="email" class="email" id="id_email"
        value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
        name="email" placeholder="Почта">
        {% if form.email.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
        {% endif %}
        <input type="password" class="password" id="id_password1"
        value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
        name="password1" placeholder="Пароль">

        {% if form.password1.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</div>
        {% endif %}

        <input type="password" class="confirmed_password" id="id_password2"
        value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
        name="password2" placeholder="Подтверждение пароля">

        {% if form.password2.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{form.password2.errors}}</div>
        {% endif %}
        
        <button type="submit" class="create_acc">Создать аккаунт</button>
    </div>
</form>
{% endblock  %}